package fr.arolla.core.question.invalid;

/**
 * Created by fmaury on 17/11/16.
 */
public class LoremIpsumQuestion extends InvalidQuestionSupport{


    @Override
    public Object questionData() {
        return "\n" +
                "\n" +
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur in quam purus. Aenean elementum id neque eget luctus. Duis placerat vulputate urna. Vestibulum orci odio, cursus id risus ac, porta congue purus. Maecenas pellentesque bibendum velit, a venenatis enim ultrices id. Etiam ut purus mattis, ullamcorper sem quis, condimentum mi. Quisque sed volutpat nunc. In quis eleifend dui.\n" +
                "\n" +
                "In interdum tortor mauris, sit amet tincidunt mauris bibendum ut. Proin eu elementum urna. Proin luctus augue vitae luctus condimentum. Sed fringilla ex in urna tincidunt luctus. Nunc ligula nulla, consequat in enim eu, pretium semper ante. Aenean vitae leo tellus. Nulla ultricies justo vel velit consequat dictum. Sed ligula ipsum, ultrices nec maximus vitae, sagittis ut velit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean luctus facilisis tristique. Mauris sit amet magna in lacus efficitur fermentum. Proin finibus lectus nec augue varius, ac euismod elit consequat. Suspendisse viverra risus ut erat mollis semper.\n" +
                "\n" +
                "Suspendisse ultricies, purus in lobortis mattis, enim nunc rhoncus sapien, vitae vehicula ipsum enim id sem. Etiam tempus justo a scelerisque commodo. Aenean venenatis felis ante, eu tristique nisi dictum feugiat. Aliquam dictum iaculis felis, in efficitur ipsum. Fusce ultricies orci urna, sodales sollicitudin elit vestibulum ut. Nullam sodales consequat elit nec egestas. Nullam non tellus commodo, rhoncus nunc id, facilisis nisl. Nulla eu massa nec diam malesuada condimentum sit amet sit amet felis. Proin dapibus placerat eros, quis ullamcorper turpis porta eu. Morbi at massa vitae justo tempor imperdiet. Duis velit nibh, sollicitudin a volutpat a, consequat vitae nisl. Donec gravida rutrum eros, id auctor justo consequat ut. Etiam tempus turpis sit amet lectus vehicula eleifend.\n" +
                "\n" +
                "Maecenas et nisl ut lorem scelerisque fermentum. Cras malesuada accumsan ante ornare rhoncus. Quisque ultrices accumsan libero dictum finibus. Cras risus libero, laoreet vestibulum eros eget, rutrum malesuada felis. Phasellus consequat sit amet erat non cursus. Curabitur fringilla, ligula ut pellentesque posuere, neque erat molestie ipsum, id elementum tellus arcu at mi. Pellentesque sed enim nisl. Maecenas nec consectetur ligula. Donec a suscipit est. Aenean commodo elementum lectus in placerat. Cras vehicula, mi vel varius rhoncus, diam ipsum gravida lorem, a tempus urna erat non mi. Duis dapibus, diam et hendrerit feugiat, nunc quam porttitor lacus, nec efficitur lectus libero ut tortor. Sed sodales sagittis quam ac dignissim. Quisque bibendum velit eget nunc dignissim euismod.\n" +
                "\n" +
                "Etiam tincidunt, dolor quis pharetra venenatis, felis mauris dignissim metus, ac dictum nulla ex et urna. Integer odio urna, maximus eu dignissim in, pulvinar vehicula dui. Suspendisse tempus porta nibh in varius. Etiam id libero arcu. Integer congue molestie rhoncus. Duis pulvinar suscipit leo, sed ultricies est tincidunt eu. Maecenas condimentum sagittis euismod. Proin nulla nulla, maximus quis porttitor et, facilisis at arcu. Nam lectus lorem, varius eget suscipit ut, aliquet sit amet augue. Praesent mollis nunc congue, suscipit lorem quis, auctor ligula. Maecenas tellus eros, faucibus nec ligula nec, eleifend laoreet nulla.\n" +
                "\n" +
                "Suspendisse laoreet dolor neque, ac commodo ex finibus et. Aliquam posuere risus in rutrum varius. In lobortis tellus id diam rutrum, a feugiat nulla dictum. Vestibulum imperdiet dui massa, id pulvinar nulla volutpat sodales. Donec sit amet enim in orci varius ultrices. Pellentesque in tellus ut enim venenatis aliquet vitae sit amet diam. Sed congue libero pulvinar velit gravida, sit amet ullamcorper lacus auctor. Vivamus felis velit, condimentum vitae enim eu, cursus feugiat erat. Nullam non justo quam. Nullam commodo dolor quis ligula suscipit tincidunt. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent tincidunt, enim a posuere sagittis, tortor felis varius lacus, eu rhoncus urna nisl nec est. Nulla placerat lorem ac dignissim lacinia. Phasellus id hendrerit lorem, eget ultricies lectus. Cras id erat iaculis neque hendrerit sodales in luctus lacus. Fusce porttitor aliquam diam non vulputate.\n" +
                "\n" +
                "Ut interdum ante non pharetra gravida. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur lorem ipsum, scelerisque eu scelerisque a, varius eget diam. Aenean eu tempor sem. Nullam ullamcorper magna vitae rutrum convallis. Donec tempus consectetur dolor, quis pretium urna molestie nec. Donec ante est, tincidunt quis condimentum vel, bibendum at nibh. In non lectus mi. In euismod ligula nec mi blandit, nec vulputate felis consequat. Integer ligula quam, lacinia id interdum eget, porttitor et diam. Vestibulum eu posuere leo. Nulla facilisis cursus velit vel bibendum. Duis laoreet lobortis aliquet. Sed mollis, leo eu tempus tincidunt, sapien felis rutrum tellus, non fringilla mi mauris et purus. Proin convallis sapien vitae quam aliquet, ac vestibulum nulla cursus.\n" +
                "\n" +
                "Praesent nulla mauris, consectetur id congue vel, feugiat ut lacus. Sed ultrices nulla et venenatis maximus. Maecenas nec ligula eu urna consequat euismod. Donec aliquam libero eu urna ullamcorper laoreet. Nam ut leo quam. Proin finibus ipsum sit amet lectus finibus hendrerit. Proin a maximus risus. Phasellus cursus massa a magna hendrerit, vitae varius augue elementum. Aliquam erat volutpat. Nunc at massa tempor, ultrices sem in, tempus lorem. Quisque mauris ante, elementum quis metus ut, malesuada laoreet leo. Fusce tincidunt dignissim tortor, non faucibus neque consectetur eget.\n" +
                "\n" +
                "Aliquam finibus augue non nibh dapibus, eu rhoncus nulla consequat. Pellentesque mattis congue ullamcorper. Proin at bibendum lacus. Nam egestas suscipit ultrices. Cras vitae volutpat justo, ac sagittis mauris. Nulla ultrices, dolor eu condimentum tincidunt, mi lectus rhoncus arcu, ac malesuada ligula ipsum at metus. Nullam fermentum, lectus quis tincidunt scelerisque, sapien ex pretium odio, nec congue mi nibh ac nunc. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam vel aliquet leo. Proin vulputate mi leo. Phasellus sagittis lobortis nulla quis gravida. Nullam mollis risus ac consequat ornare. Cras nulla quam, laoreet hendrerit est sed, tristique pulvinar nisl. In ultrices elementum hendrerit. Praesent venenatis ligula dolor. Proin vitae felis eu velit facilisis pretium quis vel tortor.\n" +
                "\n" +
                "Integer ut egestas ante. Duis vel tortor et elit eleifend venenatis at sed ex. Donec vulputate, lorem sit amet viverra blandit, eros arcu ornare erat, vitae consequat nisl massa a tortor. Integer vel maximus leo. Suspendisse varius eget sem ut finibus. Mauris ac diam mauris. Fusce non magna nec lacus egestas ornare id maximus enim. Ut sit amet scelerisque sem, ut feugiat justo. Nulla porta ipsum eu ex volutpat facilisis. Fusce vehicula ultricies orci, ac malesuada sapien venenatis vitae. ";
    }
}
